image: maven:3-jdk-11
pipelines:
  default:
    - step:
        name: Build and test
        max-time: 20
        caches:
          - maven
        script:
          - echo starting default branche Build and test ...
          - echo java --version
          - echo mvn -version
         # - mvn -s .ci/settings.xml clean verify
          - mvn -B verify
  branches:
    master:
      - step:
          name: Build and test
          max-time: 20
          caches:
            - maven
          script:
             - echo starting master branche Build and test ...
             - echo java --version
             - echo mvn -version
             - mvn -B verify
           # - mvn -s .ci/settings.xml clean verify
          artifacts:
            - target/**
      - step:
          name: Deploy to Artifactory
          max-time: 20
          caches:
            - maven
          script:
             - echo starting Deploy to Artifactory ...
           # - mvn -s .ci/settings.xml deploy
  # Manually triggered via Bitbucket UI
  custom:
    release-major-version:
      - step:
          max-time: 10
          caches:
            - maven
          script:
             - echo release-major-version ...
         #   - ./.ci/version.sh major
    release-minor-version:
      - step:
          max-time: 10
          caches:
            - maven
          script:
            - echo release-minor-version ...
         #  - ./.ci/version.sh minor
    release-patch:
      - step:
          max-time: 10
          caches:
            - maven
          script:
             - echo release-patch ...
          #  - ./.ci/version.sh patch