# Description: Pipeline for banca-online-api. This pipeline is pending to configure aws cloud. 
# See: https://hackernoon.com/deploy-to-ec2-with-aws-codedeploy-from-bitbucket-pipelines-4f403e96d50c
# Author: Jorge de Los Santos
# Version: 1.0
# Since: 03-03-2019
image: maven:3-jdk-11
pipelines:
  default:
    - step:
        name: Build and test
        max-time: 20
        caches:
          - maven
        script:
          - echo starting default branche Build and test ...
          - java --version
          - mvn -version
          - mvn -B verify
  branches:
    master:
      - step:
          name: Build and test
          max-time: 20
          caches:
            - maven
          script:
             - echo starting master branche Build and test ...
             - java --version
             - mvn -version
             - python --version
             - mvn -B verify
          artifacts:
            - target/**
      - step:
          name: Deploy to Artifactory
          image: python:3.7.2
          max-time: 1 # set to 20 later
          caches:
            - maven
          script:
             - echo starting Deploy to Artifactory ...
             - python --version
             - python -m pip install boto3
             - python $BITBUCKET_CLONE_DIR/codedeploy_deploy.py ${APPLICATION_NAME}
